INSERT INTO entity(name,address) values('Dist A','D Address A');
SET @ID = LAST_INSERT_ID();
INSERT INTO distributor(id) values(@ID);
INSERT INTO entity(name,address) values('Dist B','D Address B');
SET @ID = LAST_INSERT_ID();
INSERT INTO distributor(id) values(@ID);
INSERT INTO entity(name,address) values('Dist C','D Address C');
SET @ID = LAST_INSERT_ID();
INSERT INTO distributor(id) values(@ID);
INSERT INTO entity(name,address) values('Cust A','C Address A');
SET @ID = LAST_INSERT_ID();
INSERT INTO customer(id) values(@ID);
INSERT INTO entity(name,address) values('Cust B','C Address B');
SET @ID = LAST_INSERT_ID();
INSERT INTO customer(id) values(@ID);
INSERT INTO entity(name,address) values('Manuf A','M Address A');
SET @ID = LAST_INSERT_ID();
INSERT INTO manufacturer(id) values(@ID);
INSERT INTO entity(name,address) values('Manuf B','M Address B');
SET @ID = LAST_INSERT_ID();
INSERT INTO manufacturer(id) values(@ID);
INSERT INTO entity(name,address) values('Manuf C','M Address C');
SET @ID = LAST_INSERT_ID();
INSERT INTO manufacturer(id) values(@ID);
INSERT INTO entity(name,address) values('Manuf D','M Address D');
SET @ID = LAST_INSERT_ID();
INSERT INTO manufacturer(id) values(@ID);
INSERT INTO entity(name,address) values('Manuf E','M Address E');
SET @ID = LAST_INSERT_ID();
INSERT INTO manufacturer(id) values(@ID);
SELECT @DISTRIBUTOR_ID := id FROM entity WHERE name = 'Dist A';
SELECT @MANUFACTURER_ID := id FROM entity WHERE name = 'Manuf A';
INSERT INTO product(code,description,distributor_id,manufacturer_id) values(123,'Almonds',@DISTRIBUTOR_ID,@MANUFACTURER_ID);
SELECT @DISTRIBUTOR_ID := id FROM entity WHERE name = 'Dist A';
SELECT @MANUFACTURER_ID := id FROM entity WHERE name = 'Manuf B';
INSERT INTO product(code,description,distributor_id,manufacturer_id) values(125,'Eggs',@DISTRIBUTOR_ID,@MANUFACTURER_ID);
SELECT @DISTRIBUTOR_ID := id FROM entity WHERE name = 'Dist A';
SELECT @MANUFACTURER_ID := id FROM entity WHERE name = 'Manuf C';
INSERT INTO product(code,description,distributor_id,manufacturer_id) values(126,'Russet Potatoes',@DISTRIBUTOR_ID,@MANUFACTURER_ID);
SELECT @DISTRIBUTOR_ID := id FROM entity WHERE name = 'Dist B';
SELECT @MANUFACTURER_ID := id FROM entity WHERE name = 'Manuf D';
INSERT INTO product(code,description,distributor_id,manufacturer_id) values(127,'Onions',@DISTRIBUTOR_ID,@MANUFACTURER_ID);
SELECT @DISTRIBUTOR_ID := id FROM entity WHERE name = 'Dist C';
SELECT @MANUFACTURER_ID := id FROM entity WHERE name = 'Manuf A';
INSERT INTO product(code,description,distributor_id,manufacturer_id) values(124,'Ketchup',@DISTRIBUTOR_ID,@MANUFACTURER_ID);
SELECT @DISTRIBUTOR_ID := id FROM entity WHERE name = 'Dist C';
SELECT @MANUFACTURER_ID := id FROM entity WHERE name = 'Manuf E';
INSERT INTO product(code,description,distributor_id,manufacturer_id) values(128,'Mayonnaisse',@DISTRIBUTOR_ID,@MANUFACTURER_ID);
SELECT @CUSTOMER_ID := ID FROM entity WHERE name = 'Cust A';
SELECT @DISTRIBUTOR_ID := ID FROM entity WHERE name = 'Dist A';
INSERT INTO invoice(invoice_number,purchase_date,customer_id,distributor_id) values(1111,'22/10/2020',@CUSTOMER_ID,@DISTRIBUTOR_ID);
SELECT @CUSTOMER_ID := ID FROM entity WHERE name = 'Cust B';
SELECT @DISTRIBUTOR_ID := ID FROM entity WHERE name = 'Dist B';
INSERT INTO invoice(invoice_number,purchase_date,customer_id,distributor_id) values(1112,'24/10/2020',@CUSTOMER_ID,@DISTRIBUTOR_ID);
SELECT @CUSTOMER_ID := ID FROM entity WHERE name = 'Cust A';
SELECT @DISTRIBUTOR_ID := ID FROM entity WHERE name = 'Dist C';
INSERT INTO invoice(invoice_number,purchase_date,customer_id,distributor_id) values(1113,'26/10/2020',@CUSTOMER_ID,@DISTRIBUTOR_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1111';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '123';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(5,50,'CASE',7,@PRODUCT_ID,@INVOICE_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1111';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '125';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(10,20,'CASE',5,@PRODUCT_ID,@INVOICE_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1111';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '126';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(null,40,'WEIGHT',3,@PRODUCT_ID,@INVOICE_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1112';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '123';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(10,100,'CASE',7,@PRODUCT_ID,@INVOICE_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1112';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '127';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(null,30,'WEIGHT',2.5,@PRODUCT_ID,@INVOICE_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1113';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '124';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(12,100,'CASE',9,@PRODUCT_ID,@INVOICE_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1113';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '127';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(null,25,'WEIGHT',2.5,@PRODUCT_ID,@INVOICE_ID);
SELECT @INVOICE_ID := ID FROM invoice WHERE invoice_number = '1113';
SELECT @PRODUCT_ID := ID FROM product WHERE code = '128';
INSERT INTO invoice_line(qty,weight,unit_of_measure,unit_price,product_id,invoice_id) values(7,70,'CASE',10,@PRODUCT_ID,@INVOICE_ID);
